JuliaGPU/Metal.jl

src/execution/reflection.jl
This will be useful for debugging invalid library errors.
=> Add device_code_metallib macro

lib/core/compute-pipeline.jl, lib/core/size.jl, src/device/array.jl, src/device/metal/arguments.jl, src/execution/device_type_conversion.jl, src/execution/kernel.jl, src/state.jl
Some additional documentation in preparation for the web-based documentation. Let me know if there are other docs you want made. I stopped a bit early to work on Metal Performance Shaders.
=> Add docstrings

src/gpuarrays.jl
Fixes https://github.com/JuliaGPU/Metal.jl/issues/39
=> Fix the launch heuristic.

src/compiler/execution.jl, test/execution.jl
This will be useful for getting Metal support for AbstractKernels.
=> Add queue kernel launch argument

src/state.jl
=> Add a function for setting the current device

src/device/intrinsics/memory.jl
Closes https://github.com/JuliaGPU/Metal.jl/issues/26
=> Conditionalize the MtlDeviceArray element-type workaround.

src/device/intrinsics/simd.jl, test/device/intrinsics.jl
Adds SIMD shuffle up and down capabilities that map directly to AIR intrinsics (so required minimal changes). This is in preparation for improving mapreduce speeds with threadgroup/SIMD cooperation (#46). This code was mostly taken from my stale PR #10.
=> Add basic SIMD shuffle up/down

test/mps.jl
Got lost in a force-push in https://github.com/JuliaGPU/Metal.jl/pull/80.
=> Add MPS tests.

lib/cmt/cmt.jl, src/device/intrinsics/memory.jl, src/initialization.jl, test/runtests.jl
Fixes https://github.com/JuliaGPU/Metal.jl/issues/97
=> Support precompilation and loading on non-Apple hardware

README.md
=> Fix path the cmt in Hacking Section of the Readme

src/array.jl, test/array.jl, test/setup.jl
=> Add a mtl function for simple recursive data conversions.

docs/src/profiling.md
Just some minor cleanups to documentation formatting.  I'm excited to try this out!
=> Minor documentation formatting

docs/src/contributing.md, docs/src/faq.md, docs/src/index.md, docs/src/metal-programming.md
Given the recent interest in contributions to Metal.jl, I thought it'd be good to put some more explicit information in the docs. I wasn't sure what all to include. Should I include some sort of explanation for the CMT naming scheme ('Mtl' vs 'MTL' vs 'Mt'...etc)? Maybe I should give some pointers on Objective-C?
=> Add contributing documentation

lib/mtl/command_buf.jl
Hopefully this reveals the underlying cause of https://github.com/JuliaGPU/Metal.jl/issues/138#issuecomment-1474010435, cc @christiangnrd
=> Catch errors that happen during command buffer callbacks.

src/mapreduce.jl
Don't change grain size after pipeline creation, otherwise the maximum allowed number of threads may change, and launch parameters could be invalidated. When calculating the grain size, assume 1024 threads will be launched, which is on the conservative side (i.e. will tend to use a smaller grain size), but there should be no harm. On the plus side, the extra compilation is eliminated, so it runs slightly faster in some cases.
Before: https://gist.github.com/maxwindiff/dcb8f3bcc926cbfc3ef55940fd35f345
After: https://gist.github.com/maxwindiff/f4c361e12b738ccd21c9a96768b9501d
Alternatives considered:
* Pass grain size as a normal integer instead of a `Val`. Unfortunately this slows things down by quite a bit (10-40%).
* Iteratively calculate grain size and thread count until they converge. …
=> Do not change grain size after pipeline creation

lib/mps/linalg.jl
And make `lu` more specific by adding `MtlFloat`
=> [LU decomposition] Fix types

lib/mps/MPS.jl, lib/mps/decomposition.jl, lib/mps/kernel.jl, lib/mps/matrix.jl
=> Move MPSKernels into a dedicated file

docs/make.jl, src/compiler/reflection.jl, test/execution.jl
https://github.com/JuliaGPU/Metal.jl/pull/164#discussion_r1175627462 made me do a repo-wide search for CUDA, and I found some wrong uses that are unrelated to #164 so I made this pull request.
=> Fix some references to CUDA

src/gpuarrays.jl
Fixes https://github.com/JuliaGPU/Metal.jl/issues/162
=> Fix GPUArrays RNG interface implementation.

src/mapreduce.jl
As noted in https://discourse.julialang.org/t/help-with-autodiff-in-metal-jl/98937/4
=> Detect mapreduce threadgroup limits instead of guessing.

README.md, src/utilities.jl
Copied over from https://github.com/JuliaGPU/CUDA.jl/pull/1913.
=> Report package versions as part of versioninfo()

src/random.jl, test/random.jl
=> Add GPUArrays out-of-place random methods

lib/mtl/command_enc/blit.jl, test/metal.jl
I could not figure out how to do it with type parameters so I used metaprogramming. If there is a way, let me know and I'll change it.
Closes #192
=> Fix fill! with negative Int8 values

lib/mps/linalg.jl
=> Handle missing adjoint case.

lib/mps/MPS.jl, lib/mps/linalg.jl, lib/mps/vector.jl, test/mps.jl
before:
```julia
julia> @btime A * B;
23.166 μs (60 allocations: 1.49 KiB)
julia> @btime A * b;
161.667 μs (327 allocations: 7.23 KiB)
```
after:
```julia
julia> @btime A * b;
15.333 μs (47 allocations: 1.11 KiB)
```
=> Implement MPSVector

lib/mtl/compile-opts.jl
Low hanging fruit PR to help prepare for MacOS Sonoma.
=> Add Metal 3.1 to MTLLanguageVersion

docs/src/api/mps.md
Holdover from when I was figuring out how to organize things that I forgot to remove before submitting #235
=> Remove linear algebra section of MPS docs

src/compiler/execution.jl
Before:
```
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
Range (min … max):  11.041 μs … 197.375 μs  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     16.750 μs               ┊ GC (median):    0.00%
Time  (mean ± σ):   20.016 μs ±  11.460 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%
▅ ▁▁▃█▂
█▅█████▄▃▃▄▄▃▃▄▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▂
11 μs           Histogram: frequency by time         74.4 μs <
Memory estimate: 784 bytes, allocs estimate: 32.
```
After:
```
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
Range (min … max):   5.584 μs … 452.500 μs  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):      6.333 μs               ┊ GC (median):    0.00%
Time  (mean ± σ):   20.696 μs ±  31.537 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%
█▅▄▂▁ …
```
=> Reduce launch overhead by generating code to encode arguments.

Project.toml, lib/mtl/resource.jl, src/array.jl, src/broadcast.jl, src/compiler/execution.jl, test/array.jl
Similar to https://github.com/JuliaGPU/CUDA.jl/pull/2203. As part of this, adapts to Adapt.jl 4 and GPUArrays.jl 10.
=> Preserve storage mode when broadcasting.

src/device/intrinsics/memory.jl
Works around https://github.com/JuliaGPU/Metal.jl/issues/282
=> Avoid redundant pointer conversions for threadgroup memory.

src/array.jl, test/array.jl
Addresses both potential issues brought up in #289.
=> Address potentiallly buggy `mtl` behaviour.

src/array.jl
Fix mixed example from #305 and remove example for functionality removed in #290.
=> Fix doctests

.gitignore, Project.toml, lib/mtl/buffer.jl, src/array.jl, src/compiler/execution.jl, src/memory.jl, src/pool.jl, test/array.jl, test/metal.jl
Fixes a few consistency/style things and removes a non-existent Metal API function.
=> Minor cleanup

test/profiling.jl
Closes https://github.com/JuliaGPU/Metal.jl/issues/281
As suggested by @christiangnrd
=> Re-enable profiling tests on M1/14.4 when using Xcode 15.3.

docs/src/api/kernel.md, src/device/array.jl
=> Small typo and doc fixup

test/runtests.jl
To debug https://github.com/JuliaGPU/Metal.jl/issues/329
=> Trigger the runtime profiler when a test times out.

lib/mps/matrix.jl, test/mps.jl
And the option to create an MPSMatrix from an MtlVector. Useful since many kernels are only available for MPSMatrix and not MPSVector.
Should be a much quicker review than MPSMatrixRandom ;)
=> Add MPSMatrixSoftMax

src/array.jl
=> [NFC] Fix indentation

lib/mtl/buffer.jl
=> Don't export non-existent `contents`

src/device/intrinsics/version.jl, src/device/pointer.jl
https://github.com/JuliaGPU/Metal.jl/issues/358#issuecomment-2150831644
=> Unexport `SimpleVersion` and `AS`

lib/mtl/compile-opts.jl, lib/mtl/device.jl, lib/mtl/version.jl
I was not able to figure out how to see the metallib support version so I left that as-is.
=> Initial MacOS 15 support

test/examples.jl
There's no need to launch new Julia processes, which is slow.
=> Simplify testing of examples.

src/initialization.jl
Otherwise we run into the following assertion anyway: https://github.com/JuliaGPU/Metal.jl/blob/2e77220bebb82d5f729b5fdbd184967c1e5db1e9/src/compiler/compilation.jl#L85-L86
cc @jpsamaroo
=> Check the macOS version during initialization.

src/Metal.jl, src/accumulate.jl, test/array.jl
This PR port the scan kernel from [CUDA.jl](https://github.com/JuliaGPU/CUDA.jl/blob/master/src/accumulate.jl).
=> Add `accumulate` implementation

src/Metal.jl, src/indexing.jl, test/array.jl
This PR port `findall` from [CUDA.jl](https://github.com/JuliaGPU/CUDA.jl/blob/master/src/indexing.jl).
=> add `findall` implementation

docs/src/api/array.md
=> Fix typo in docs

Project.toml, ext/SpecialFunctionsExt.jl, src/Metal.jl, src/initialization.jl
No longer needed now that all supported versions support extensions.
=> Remove Requires dependency

src/compiler/library.jl, src/compiler/reflection.jl
Fixes https://github.com/JuliaGPU/Metal.jl/issues/388
=> Reflection: Figure out kernel names by looking at metallib section.

ext/SpecialFunctionsExt.jl, test/device/intrinsics.jl
=> Add erfinv

lib/mps/command_buf.jl, lib/mps/matrix.jl, src/compiler/library.jl, src/compiler/reflection.jl, src/gpuarrays.jl, src/mapreduce.jl
Also removes code mentioned in #397. I can remove that commit if that code ends up being important.
Closes #397
=> Cleanup some imports

src/device/intrinsics/memory.jl
=> Remove type-pirated function

test/array.jl
fixes https://github.com/JuliaGPU/Metal.jl/issues/389
=> Add tests for broadcasting minimum and maximum

lib/mps/matrixrandom.jl, test/mps/matrix.jl
Also add simple test that only checks that nothing errors
=> Fix `MPS.synchronize_state`

test/mps/copy.jl
The improvement that sparked #438.
=> NFC tweak to MPSMatrixCopy tests

.github/workflows/Formatting.yml, .github/workflows/Loading.yml
=> Add Runic action to suggest formatting changes.

.github/workflows/Benchmark.yml
Maybe fix #516
Will have to be merged before we know if it it helps.
=> Increase polling interval for benchmark action

src/device/intrinsics/simd.jl, test/device/intrinsics.jl
=> Test both simd shuffle intrinsics.

src/device/intrinsics/math.jl, test/device/intrinsics.jl
Close #552 with suggestions from https://github.com/JuliaGPU/Metal.jl/issues/552#issuecomment-2693546295 (and code from CUDA.jl)
=> Support pow with Int exponent

src/array.jl, test/array.jl
There's some really weird behaviour here as shown by the tests marked as broken
=> Fixes and more tests for `unsafe_wrap`

lib/mps/random.jl, lib/mpsgraphs/execution.jl, lib/mpsgraphs/matmul.jl, src/indexing.jl, test/array.jl, test/random.jl
=> Fix some type ambiguities

test/linalg.jl, test/mpsgraphs/random.jl
Does it make sense that half multiplication precision changed between macOS 13 and 14?
=> Fix tests for macOS 13

Project.toml, README.md
Also minor updates to the readme
Close #593
=> Bump version

src/indexing.jl, test/array.jl
Analoguous to https://github.com/JuliaGPU/CUDA.jl/pull/2554
=> Fix findall with empty MtlArray of Bool

lib/mtl/command_enc/compute.jl, src/version.jl
Also add `dispatchThreads`
These are unrelated so probably best not to squash.
=> Tahoe versions

examples/flopscomp.jl, src/utilities.jl, test/version.jl
This could enable the same heuristic used in CUDA.jl to decide between reduction by block/group or reduction by thread
=> Add function to retrieve # of gpu cores in system

lib/mps/MPS.jl, lib/mpsgraphs/core.jl, lib/mpsgraphs/execution.jl, lib/mpsgraphs/libmpsgraph.jl, res/wrap/libmpsgraph.toml, test/mpsgraphs/core.jl
This should allow for serializing graphs into mpsgraphpackages for visualization in XCode
=> More `MPSGraphs` API

Project.toml, README.md, src/mapreduce.jl, src/utilities.jl, test/array.jl
Closes #661
And a few improvements. Fix and tests should be split off and merged/released asap if any of the other changes require further discussion.
@cncastillo Can you verify that this fixes your issues?
=> Fix serial reductions

src/MetalKernels.jl
https://github.com/JuliaGPU/KernelAbstractions.jl/issues/634
=> Fix type instability in `KA.allocate`
