JuliaGPU/Metal.jl

.buildkite/pipeline.yml, test/runtests.jl
Ideally, I'd like to do the same with the Metal LLVM back-end, but since we can't do an out-of-tree build (i.e. we really have to build most of LLVM, and can't just download the LLVM JLL like LLVM_Extra does) that would probably take too long.
=> First test with a locally-built cmt.

README.md, deps/cmt/CMakeLists.txt, deps/cmt/include/cmt/capture/capture_descriptor.h, deps/cmt/include/cmt/capture/capture_manager.h, deps/cmt/include/cmt/capture/capture_scope.h, deps/cmt/include/cmt/cmt.h, deps/cmt/include/cmt/enums.h, deps/cmt/include/cmt/types_metal.h, deps/cmt/include/impl/conversion.h, deps/cmt/src/capture/capture_descriptor.m, deps/cmt/src/capture/capture_manager.m, deps/cmt/src/capture/capture_scope.m, lib/core/MTL.jl, lib/core/libcmt.jl, lib/core/profile.jl, src/utilities.jl, test/profiling.jl, test/runtests.jl
This would add profiling for later viewing by Xcode. However, I've run into some odd errors when trying to view with Xcode. Sometimes trying to replay the GPU trace will result in "Failed to enable shader profiler. (516)" while other times it works flawlessly. I haven't been able to determine what causes this. Additionally, if I try to replay more than one GPU trace at a time, all but the first GPU trace report that no performance data was found.
My testing has been on an M1 Macbook Air with the 7-core GPU running MacOS 13.0 and Julia 1.8.2.
=> Add GPU profiling capabilities

src/compiler/execution.jl, src/mapreduce.jl
This uses warp intrinsics to accelerate mapreduce (but doesn't fix a larger underlying issue causing the majority of its slow performance #46). In simple testing, resulted in significant (~2x) speedups for large, non-inplace reductions.
Dependent on #73.
=> Optimize warp reduction for mapreduce

src/gpuarrays.jl
This reduces the overhead incurred by the broadcast kernel over a handwritten kernel (at sufficiently large array sizes) by ~45%.
These benchmarks are ran on a M1 Pro laptop.
First number is the speed of a handwritten addition kernel. Second number is the speed of `@. c = a + b`.
=== At https://github.com/JuliaGPU/Metal.jl/commit/6bb5bb08a44444efdee9c2b747f6aa6399d79e3c
```julia
julia> include("bench.jl"); bench(1024*1000); bench(1024*10000); bench(1024*100000);
[ Info: Precompiling Metal [dde4c033-4e86-420c-a63e-0dd931031962]
n = 1024000
285.167 μs (160 allocations: 4.16 KiB)
337.250 μs (202 allocations: 6.05 KiB)
n = 10240000
632.333 μs (160 allocations: 4.16 KiB)
842.916 μs (202 allocations: 6.05 KiB)
n = 102400000
3.624 ms (160 allocations: 4.16 KiB)
5.553 ms (202 allocations: 6.05 …
```
=> Specialize GPUArrays.global_index() to improve broadcast performance

src/array.jl, src/memory.jl, test/metal.jl
Used to implement `async_copy!` in [KernelAbstractions.jl](https://github.com/tgymnich/KernelAbstractions.jl/blob/83951cdcfa3e63d9b3ef50fbb8f1b45baaa33896/lib/MetalKernels/src/MetalKernels.jl#L125).
=> Add queue parameter to unsafe_copyto

src/mapreduce.jl
Improve indexing performance by passing `CartesianIndices` statically, using a similar trick as https://github.com/JuliaGPU/GPUArrays.jl/pull/454. Still slow, but not as bad as before. Helps with https://github.com/JuliaGPU/Metal.jl/issues/46.
Before:
```julia
julia> a = fill(Float32(1.0), 4096 * 4096);
julia> da = MtlArray(a);
julia> b = fill(Float32(1.0), 4096, 4096);
julia> db = MtlArray(b);
julia> @btime sum(a)
1.393 ms (1 allocation: 16 bytes)
1.6777216f7
julia> @btime sum(b)
1.392 ms (1 allocation: 16 bytes)
1.6777216f7
julia> @btime sum(da)
4.026 ms (868 allocations: 23.95 KiB)
1.6777216f7
julia> @btime sum(db)
11.196 ms (873 allocations: 25.23 KiB)
1.6777216f7
```
After:
```julia
julia> @btime sum(da)
1.811 ms (754 allocations: 20.80 KiB)
1.6777216f7
julia> @btime sum(db)
2.181 ms …
```
=> Improve reduce performance by passing CartesianIndices and length statically

examples/gtk.jl
Will segfault until #102 is in.  Unsure what will happen on a headless CI box.
=> Add example showing Metal and Gtk4 integration

lib/mtl/command_enc/blit.jl
This looks like a three year old typo that probably snuck in during a debugging session.  
I will one day create a way to run the tests so that they will report objective-C memory issues, but as far as I can tell for now, this fix is correct, or at least consistent with everything else.
=> Fix memory leak.

README.md, src/utilities.jl, test/profiling.jl
Makes it behave like Nsight, which is much easier than having to keep your session alive because the gputrace might otherwise get deleted.
=> Write profile trace in the current folder.

src/mapreduce.jl
Using ideas from:
* https://kieber-emmons.medium.com/optimizing-parallel-reduction-in-metal-for-apple-m1-8e8677b49b01
* https://developer.download.nvidia.com/assets/cuda/files/reduction.pdf
This replaces the old "reduce serially across chunks of input vector that don't fit in a group" loop, which doesn't seem to apply to Metal.jl since we always launch enough threadgroups to cover the entire input.
In a simple test this is 2-3x faster than HEAD and achieves > 130GB/s in the 1D reduction case. I'll need to experiment with the ~~stride~~ grain size parameter and document it, and test more complex cases like such as non-power-of-2 sizes or reducing only certain dimensions.
Before:
```julia
function init(dims...)
a = Array{Float32}(undef, dims...)
for i in 1:length(a)
a[i] = 1
end
return (a, …
```
=> Reduce multiple consecutive values in each thread to improve efficiency

README.md, examples/gtk.jl, examples/peakflops.jl, examples/unified_memory.jl, src/compiler/execution.jl, src/gpuarrays.jl, src/mapreduce.jl, test/execution.jl
Prior to this PR,  Metal.jl was using the term `grid` in a way that is inconsistent with Apple's terminology.  
Things to consider adding to this PR
=> Rename grid to groups

src/compiler/execution.jl, test/execution.jl
This is what GPUCompiler's validator expects.
=> Support passing non-isbits arguments, as long as they're unused.

src/compiler/reflection.jl
Fixes the following error:
```julia
julia> Metal.code_llvm(stdout, () -> nothing, ())
ERROR: MethodError: no method matching device()
```
=> Call the correct current_device() in reflection

src/device/intrinsics/arguments.jl, test/device/intrinsics.jl
=> Error when calling device functions on CPU

README.md
I don't know if removing it or mentioning that it is no longer used would be better, but it's a bit confusing in its current state to reference cmt since it is no longer used.
[Skip-tests]
=> Remove reference to no longer used library in README.md

lib/mtl/command_buf.jl
Works around https://github.com/JuliaGPU/Metal.jl/issues/138; we already had to support async callbacks for Julia 1.8, so let's use those on 1.9 too.
=> Don't rely on thread adoption for command buffer callbacks.

lib/mtl/MTL.jl
Closes #179 
I went with `uname` instead of the suggestion in issue #179 for simplicity and the fact that either method would only ever get called once per load so speed isn't very important here. 
I'm not opposed to using the other function (and giving credit) if anyone feels strongly about it.
@tgymnich What do you think?
=> Fix Darwin version indentification

.gitignore
So that I (and others) don't accidentally push it.
See #147 for an example.
=> Add `*.DS_Store` to `.gitignore`

lib/mps/linalg.jl
Sorry for that oversight, but this is required on older julia versions.
=> disambiguate `gemm_wrapper!` with LinAlg.jl

lib/mps/matrix.jl
This wasn't covered by CI because due to missing `mul!` specializations, we weren't actually using MPS for transposed matmul.
x-ref https://github.com/JuliaGPU/Metal.jl/pull/197#issuecomment-1571873753
=> Fix transposed matmul.

Manifest.toml, src/array.jl, test/array.jl
Fixes https://github.com/JuliaGPU/Metal.jl/issues/205
Requires https://github.com/JuliaGPU/KernelAbstractions.jl/pull/402
=> Disallow Float64 arrays entirely.

lib/mtl/MTL.jl, src/Metal.jl, src/compiler/compilation.jl, src/compiler/execution.jl, src/device/intrinsics/atomics.jl, src/device/intrinsics/version.jl, src/pool.jl, test/device/intrinsics.jl, test/execution.jl
Fixes https://github.com/JuliaGPU/Metal.jl/issues/79
Depends on https://github.com/JuliaGPU/GPUCompiler.jl/pull/436, https://github.com/JuliaGPU/Metal.jl/pull/169
Doesn't contain all low-level atomics yet, and still needs some high-level magic on top of that (i.e. `@atomic`).
=> Implement atomics using compiler intrinsics

src/device/intrinsics/math.jl, test/device/intrinsics.jl
Fix #229 
I would add tests for these changes, but I'm not really sure where in the test suite to add them.
=> Fix argument types in sincos

README.md, docs/make.jl, docs/src/api/array.md, docs/src/api/kernel.md, docs/src/api/mps.md, docs/src/faq/contributing.md, docs/src/faq/faq.md, docs/src/index.md, docs/src/profiling.md, docs/src/usage/array.md, docs/src/usage/kernel.md, docs/src/usage/overview.md, lib/mps/matrix.jl, lib/mps/vector.jl, src/array.jl
- Fix some typos
- Repair/remove broken links
- Reorganize to match CUDA.jl better and include already-written documentation
- `Julia packages` is not shown in the Metal v0.3 `Metal.versioninfo()`. So fix that. I used v1.9.3 because that version avoids the intermittent bus errors (see #225)
This also fixes the doctests which prevented the 0.5.0 docs from being generated.
[Doc preview](https://metal.juliagpu.org/previews/PR235/)
=> Improve docs

src/device/intrinsics/math.jl, test/device/intrinsics.jl
(Replaces #236)
`Base.Math.log1p` calculation relies on two procedures , [log_proc1](https://github.com/JuliaLang/julia/blob/15b590bd6a1f17f3859752594d5d8ff534cd38b3/base/special/log.jl#L222) and [log_proc2](https://github.com/JuliaLang/julia/blob/15b590bd6a1f17f3859752594d5d8ff534cd38b3/base/special/log.jl#L245) from the literature [Tang (1990)](https://dl.acm.org/doi/pdf/10.1145/98267.98294). The current implementation upscales to `Float64` internally and as such is incompatible with Metal.
See also relevant discussions #234, #236
This PR ports [`log1pf` from openlibm](https://github.com/JuliaMath/openlibm/blob/master/src/s_log1pf.c)
This implementation v. the original C implementation (`Float32`)
```
max 1.0 at x = 3.0777041e38
mean 0.00010909553601139363
```
This implementation v. …
=> Port openlibm log1pf as log1p

lib/mps/matrix.jl, lib/mps/vector.jl, test/mps.jl
- add properties
- create batch of MPSMatrices
=> MPSMatrix improvements

src/array.jl, test/array.jl
Fixes #277. I'm not familiar with the internals of `Metal.jl` or `CUDA.jl` so it's very possible I am doing something wrong with the memory management.
As suggested by @maleadt in https://github.com/JuliaGPU/Metal.jl/issues/277#issuecomment-1914195535 I tried to follow the implementation of `resize!` from `CUDA.jl`.
I also added tests based on the ones for `resize!` in `CUDA.jl`.
=> Add `resize!`

lib/mps/MPS.jl, lib/mps/images.jl, lib/mps/size.jl, lib/mtl/MTL.jl, lib/mtl/size.jl, lib/mtl/texture.jl
Initial attempt at implementing `MTLTexture`, along with some "simple" MPS image filters that I used to test the implementation. I wrote this a few months ago but couldn't figure how to get it working on non-square images.
I'm creating this draft PR in case someone can help me figure out what's going on (or take over).
`MTLTexture` is needed to implement `MPSImage`, which is needed for all the Metal Performance Shaders convolutional neural network functionality.
=> Initial MTLTexture support

src/memory.jl
In https://github.com/JuliaInterop/ObjectiveC.jl/pull/26, we're now relying on `pointer(obj)` to return an `id` pointer. Metal.jl had a custom `pointer` method for `MTLBuffer`, which turns out problematic.
=> Remove an unneeded pointer method.

src/array.jl, test/array.jl
This PR does 3 things:
- Adds a check for the unsupported `Int128` and `UInt128` when constructing a `MtlArray`. (https://github.com/JuliaGPU/Metal.jl/issues/287#issuecomment-1967391570)
- Simplifies the opinionated `adapt_storage` to only convert `Float64` -> `Float32`. This also makes `BigFloat` no longer get converted to Float32. Add tests for every supported scalar type. (also https://github.com/JuliaGPU/Metal.jl/issues/287#issuecomment-1967391570)
- I forgot to add a function for the regular constructor when I parameterized the storagemode in #194, so add that and add tests
Closes #287
Closes #289
I can spin off point 3 into its own PR if the other 2 need more discussion.
=> `adapt_storage`-related improvements

docs/src/profiling.md, src/Metal.jl, src/compiler/compilation.jl, src/pool.jl, src/state.jl, src/utilities.jl
This offers similar functionality to NVTX.jl in CUDA land.
Example:
```julia
using Metal
using ObjectiveC, .OS
function main(N = 10_000_000)
a = rand(Float32, N)
da = MtlArray(a)
Metal.@profile begin
for i in 1:10
@signpost_interval start="iteration $i" "sum" sum(da)
end
end
Metal.unsafe_free!(da)
return
end
isinteractive() || main()
```
You can see the `sum` interval as part of the default logger, as well as some Metal.jl-internal ones I've opted to include.
=> Add support for signposts

src/compiler/compilation.jl
When `throw`ing in a catch block, the previously-caught `NSError` will be rendered as part of the exception stack. This is an issue, as it may have been freed already at that point. Maybe this hints to a fragile pattern we ought to somehow avoid in ObjectiveC.jl, but for now let's just tackle this very issue.
Fixes https://github.com/JuliaGPU/Metal.jl/issues/301
=> Retain NSError we rethrow to avoid an UAF.

src/device/intrinsics/simd.jl, src/mapreduce.jl
The grain heuristic was suboptimal, as it resulted in unnecessary launches (cc @maxwindiff):
```
julia> sum(mtl(rand(10_240_000)))
Reducing (10240000,) to (1,)
Reducing (1, 2500) to (1, 1)
Reducing (1, 1, 2) to (1, 1, 1)
5.1199045f6
```
Now:
```
julia> sum(mtl(rand(10_240_000)))
Reducing (10240000,) to (1,)
Reducing (1, 2500) to (1, 1)
5.1215505f6
```
This doesn't affect performance much though. In fact, it looks like mapreduce performs reasonably well after https://github.com/JuliaGPU/Metal.jl/pull/123. Using this to measure:
```julia
using Metal
using Chairmarks
function memcopy(output_data::AbstractArray{T}, input_data::AbstractArray{T}) where T
i = thread_position_in_grid_1d()
if 1 <= i <= length(input_data)
@inbounds output_data[i] = input_data[i]
end
return
end
function main(N=2^26) …
```
=> Minor mapreduce improvements

.buildkite/pipeline.yml
Also disable nightly until it's on a different LLVM version as 1.11.
Should nightly stay enabled?
=> Add 1.11 CI

src/broadcast.jl, test/metal.jl
By using hardware 2d/3d indices whenever possible.
Benchmark script:
```julia
using Metal
using Chairmarks
function memcopy(output_data::AbstractArray{T}, input_data::AbstractArray{T}) where T
i = thread_position_in_grid_1d()
if 1 <= i <= length(input_data)
@inbounds output_data[i] = input_data[i]
end
return
end
function test(dims; T=Float32)
cpu_in = rand(T, dims)
gpu_in = MtlArray(cpu_in)
gpu_out = similar(gpu_in)
print(join(dims, "×"), "-element $T (", Base.format_bytes(sizeof(cpu_in)), "): ")
gpu_out .= gpu_in
@assert Array(gpu_in) == Array(gpu_out)
threads = 256
groups = cld(length(cpu_in), threads)
bench = @b Metal.@sync @metal threads=threads groups=groups memcopy(gpu_out, gpu_in)
reference = Base.format_bytes(2*sizeof(gpu_in) / bench.time) * "/s"
bench = @b Metal.@sync (gpu_out .= …
```
=> Specialize broadcast to avoid integer divisions.

test/runtests.jl
Seems like the mapreduce test has a high variability in duration and in 1.8 it sometimes goes over the 300 second limit.
Add an extra minute to hopefully prevent the timeout from accidentally being reached.
=> Increase test timeout limit to accomodate 1.8

.buildkite/pipeline.yml, .gitignore, LocalPreferences.toml, Project.toml, src/Metal.jl, src/array.jl, src/utilities.jl, test/array.jl, test/runtests.jl
Addresses https://github.com/JuliaGPU/Metal.jl/issues/312#issuecomment-1988304979 and closes #312.
=> Test all storage modes

src/MetalKernels.jl, src/array.jl
=> Fix KernelAbstractions for Unified Memory

lib/mtl/buffer.jl, src/array.jl, src/memory.jl, test/array.jl
Feedback on implementation, interface, tests, etc. is welcome.
Closes #62
=> Create MtlArray using memory allocated by Array

lib/mtl/version.jl, src/initialization.jl, src/utilities.jl
Metal.jl does not seem to work under Rosetta (#338) so add a warning for now until we find a fix.
=> Add error message for running Metal.jl under Rosetta

lib/mtl/version.jl, src/initialization.jl, src/utilities.jl
Asking for `sysctl.proc_translated` on non Apple Silicon platforms returns ENOENT. Also the issue this is meant to warn for also occurs on non rosetta x86
reverts #339
=> Revert error message for Rosetta

lib/mps/MPS.jl, lib/mps/command_buf.jl, lib/mps/linalg.jl, lib/mtl/command_buf.jl, test/mps/copy.jl
Add `MPSCommandBuffer` and use it with the LinearAlgebra integrations that would benefit from using it.
No speedup with `LinearAlgebra.lu!`, but allocations go from 488 to 466. Similar story for the allocating version.
=> Add `MPSCommandBuffer`

lib/mps/MPS.jl, lib/mps/command_buf.jl, lib/mps/copy.jl, lib/mps/decomposition.jl, lib/mps/linalg.jl, lib/mps/matrix.jl, lib/mps/vector.jl
The idea is to add automatic memory management to interface implementation methods, so that callers don't ever have to think about memory management. Internal methods do not need to be annotated as such, because it's expected that they will be called from a context where an autoreleasepool is active.
This required additional fixes/changes:
- matrix/... descriptors are allocated by a factory method, so do not need to be released (this was a TODO)
- MPSCommandBuffer objects similarly are created by a factory, so _should not_ be manually released
I also did some light formatting while going through this code.
=> Add autoreleasepools to MPS interface methods.

lib/mps/command_buf.jl, lib/mps/linalg.jl, lib/mtl/command_buf.jl
I get why we return the cmdbuf from do-block constructors, to reuse it after the commit, but it seems redundant to return the object from commit methods that already took it as an argument in the first place.
Instead, return the value returned by the callable.
I think this was an oversight with the original MTLCommandBuffer interface in the first place, given the `ret` variable.
=> Don't redundantly return the cmdbuf from commit methods.

src/device/quirks.jl, test/device/intrinsics.jl
Fixes #364.
@maleadt this was the most minimal implementation I could come up with.
I override two functions:
1. `Base.Math.exponent(::Base.IEEEFloat)` in order to avoid exception throws.
2. `Base.ssqs(x::T, y::T) where T<:Real` to avoid a `Union` type in type inference by changing [this line](https://github.com/JuliaLang/julia/blob/a14cc38512b6daab6b8417ebb8a64fc794ff89cc/base/complex.jl#L523) to `k = m==0 ? 0 : exponent(m)`.
I wonder if 2. should be fixed in Base. The Base version effectively sets `k` to `zero(m)` rather than `0` if `iszero(m)`, however `k` is supposed to be `Int` anyway. The way that I changed it, it would probably mean that Base wouldn't need to have so many type asserts for `k` (there is one in `Base.ssqs` and one in `Base.sqrt(z::Complex)`).
=> Define complex sqrt

src/device/array.jl
The derived device array functions are not calling the device array constructor correctly, fixed by reordering the arguments.
=> fix derived device array

src/device/intrinsics/math.jl, test/array.jl
The `Base.ReshapedArray` is using `Int128` for computing the indices with `Base.MultiplicativeInverses._mul_high`. This PR adds a device override to avoid `Int128`. Without this PR, the test will error out with "unsupported use of i128 value".
fixes  #332
=> avoid ReshapedArray using Int128 in metal kernel

src/array.jl
Without this PR:
```julia-repl
julia> using Metal, Test
julia> @inferred reshape(mtl([1]), (1,1))
ERROR: return type MtlMatrix{Int64, Private} does not match inferred return type MtlMatrix{Int64}
```
With:
```julia-repl
julia> using Metal, Test
julia> @inferred reshape(mtl([1]), (1,1))
1×1 MtlMatrix{Int64, Private}:
1
```
=> improve type stability of derived array

lib/mps/images.jl, lib/mps/matrix.jl
These functions were kind of just thrown in from when I was newer to contributing. The topk functions are fine but feel out of place, but the blurring functions were mostly for testing the filters, and I don't think they should be used in their current form.
I think we should unexport while we have breaking changes waiting to be released, and reintroduce in a more thought-out form in the future.
=> Unexport some high-level MPS functionality from `MPS`

src/initialization.jl
Since https://github.com/JuliaLang/julia/pull/55210, `Base.active_repl_backend` is not always defined.
"Passing" tests would be that the nightly tests fail but not immediately.
=> Adapt to new REPL precompile changes (JuliaLang/julia#55210)

.buildkite/pipeline.yml
Should have been fixed by https://github.com/JuliaGPU/GPUCompiler.jl/pull/618, which is part of GPUCompiler 0.27.2
Closes https://github.com/JuliaGPU/Metal.jl/issues/370
=> Make 1.11 CI success mandatory.

docs/src/usage/array.md, lib/mps/MPS.jl, lib/mps/matrixrandom.jl, lib/mps/random.jl, src/random.jl, test/mps/copy.jl, test/random.jl
Adds https://developer.apple.com/documentation/metalperformanceshaders/mpsmatrixrandom?language=objc and the other "MPSMatrixRandom" classes.
=> Add `MPSMatrixRandom`

docs/src/usage/kernel.md
Unfortunately this course material seems to have been removed from the University of Illinois website, and the wayback machine version exists but no links to the actual materials work, so I propose removing it.
=> Remove broken link in Docs

Project.toml
We don't have a [target] in our manifest so I don't believe this is needed.
=> Remove unused [extras] section in Project.toml

lib/mps/matrixrandom.jl, src/compiler/compilation.jl
Make the default argument for `_mpsmat_rand!` slightly more correct.
Also fix a couple unrelated typos that I caught while exploring.
=> Small fix and typos

.buildkite/pipeline.yml
Considering this is in the `julia` queue instead of the `juliaecosystem` queue, should the macOS 15 runner only run the output tests?
I mostly created this PR to test if anything special was needed to run tests on the `julia` queue.
=> Add CI for macOS 15

lib/mps/linalg.jl, test/mps/linalg.jl
=> Make `lu` results have same storage mode as input

test/array.jl
=> Get more descriptive errors from flaky test

.buildkite/pipeline.yml, src/array.jl
No need to run nightly when we know it'll fail considering the current Apple silicon runner situation
=> Disable nightly CI and fix invalid Metal API usage

.github/workflows/Benchmark.yml
I don't know if this'll work, we'll have to commit and see :)
=> Don't report benchmarks on main branch commits

perf/array.jl, src/array.jl, src/device/array.jl, test/array.jl
=> Fix #451 and a couple other fixes

src/array.jl, test/array.jl
Use CPU copy for shared storage arrays to avoid ObjectiveC.jl overhead.
Is this even a good idea?
Depends on #452
=> Use CPU copy with SharedStorage

ext/BFloat16sExt.jl
Otherwise the extension cannot precompile on non-Apple devices.
=> Only load BFloat16s extension on Apple systems

lib/mtl/buffer.jl, src/initialization.jl
Closes #457 
Closes #458
Backport to 1.4?
=> Fix loading on unsupported platforms

.buildkite/pipeline.yml, src/memory.jl, test/capturing.jl, test/execution.jl, test/setup.jl
Not worth running a test we know will fail with only one apple silicon runner.
=> Add more tests to api validation testing

.buildkite/pipeline.yml, lib/mtl/library.jl, src/array.jl, src/compiler/reflection.jl, src/device/intrinsics/memory.jl, src/initialization.jl, test/array.jl, test/capturing.jl, test/execution.jl, test/mps/linalg.jl
We don't support macOS version prior to 13 so remove related code.
Also replace some uses of `x == nothing` to `x === nothing`.
Diff best looked at with "hide whitespace" option
=> Remove old code and test cleanup

.buildkite/pipeline.yml, .github/workflows/Benchmark.yml
=> Don't run benchmarks from fork

lib/mtl/buffer.jl, src/initialization.jl, src/version.jl
Ref https://github.com/JuliaLang/julia/pull/55793
=> Use `OncePerProcess` in 1.12+

lib/mps/matrix.jl, test/mps/copy.jl
MPSDataType enum definition had incorrect Complex numbers definitions. I also forgot that adjoint and transpose  are different for those types when I originally wrote the test.
Only the first and last commit have functional changes
=> Fix copy tests

src/MetalKernels.jl, test/array.jl
Implementation borrowed from [CUDA.jl version.](https://github.com/JuliaGPU/CUDA.jl/blob/ca8f6cfa13a244ce9825a21c82a3d55bfd72f813/src/CUDAKernels.jl#L147-L151)
Close #466
=> Fix global linear indexing (`fill!`)

lib/mps/MPS.jl, lib/mps/kernel.jl, lib/mps/ndarray.jl, test/mps/ndarray.jl
Not hooked up to any higher-level features but comes with tests.
=> Initial support for MPSNDArray

lib/mps/MPS.jl, lib/mps/matrix.jl, lib/mps/ndarray.jl, test/mps/ndarray.jl
I realized automatically reversing dimensions in the descriptor as part of the low-level wrappers is a terrible idea.
Also a few more improvements
Also using this as an opportunity to test the [skip benchmark] and benchmarking from a fork. Edit: It works
=> Fix `MPSNDArrayDescriptor` wrapper

test/random.jl
As part of our random tests, we verify is that at least one of the values in an array is no longer 0. We test the generation of length 1 arrays of `(U)Int8`. That gives each run of those tests a 1/256 chance of generating a 0 and erroneously failing our test suite. See [the latest such failure](https://buildkite.com/julialang/metal-dot-jl/builds/1545#0193e49a-3f9b-472b-becc-13d329d18b7b).
This PR makes tests that have such a high chance of failing try again before declaring a failure so we don't have to deal with a false failure every few days.
My solution feels overengineered so I'm open to suggestions for a simpler implementation.
=> Rerun random tests with chance of false negative once.

lib/mtl/libmtl.jl, res/wrap/libmps.toml, res/wrap/libmtl.toml, res/wrap/wrap.jl
The added functions are not super useful since they're essentially constructors, but this removes the piracy of `Generators.skip_check`.
Ignore MPS functions since MPS does not seem to have a dylib. If anyone ever needs those functions I can look into it.
Also a few improvements to wrap.jl to make developing easier.
=> Followup to #492: Enable C function wrapping

.github/workflows/ci.yml, lib/mps/ndarray.jl, lib/mtl/device.jl, src/state.jl, src/version.jl, test/runtests.jl, test/setup.jl
=> Test loading of package on unsupported platforms

test/mtl/metal.jl
Noticed it's no longer broken on 15.3.
=> Enable `add_functions!` test under shader validation

src/compiler/execution.jl, test/execution.jl
=> Add error checking to command buffer completion handler

src/device/intrinsics/math.jl, test/device/intrinsics.jl
Replaces #529 
Description of each commit in order:
- `tanpi` has been in base Julia since 1.10, so switch from `@device_function` to `@device_override`.
- Test all currently-defined float intrinsics and slightly refactor the old ones.
- List the float intrinsics from the metal shading language in the tests.
- Add intrinsics for `clamp` & `sign`
- Add intrinsics for `nextafter`
- Add intrinsics for 2-arg `atan`
- Add intrinsics for 3-arg `max` & 'min'
=> Improvements to float intrinsics

src/device/intrinsics/math.jl, test/device/intrinsics.jl
Also same treatment to the Float32 intrinsics since I don't know why it used to work.
Closes #530
=> Fix Float16 sincos intrinsic

lib/mps/ndarray.jl, test/mps/ndarray.jl
2 functions aren't actually limited to macOS 15. I don't understand why I thought they were. Also a few fixes for running tests on macOS 13.
=> Version-related fixes to MPSNDArray

test/runtests.jl
It's always installed on CI and some people may want to run tests locally without having to install XCode.
In my case I don't want to install xcode a 3rd time on my macOS 13 volume.
=> [tests] Assume compatible system if xcode not installed

lib/mps/vector.jl, src/array.jl, src/compiler/execution.jl, src/device/array.jl, src/device/intrinsics/memory.jl, src/pool.jl, test/array.jl, test/runtests.jl
Fixes lines where indents are 2 spaces instead of 4.
This also fixes the REPL docstring highlighting for `resize!` and `mtlconvert`.
Closes #543
=> [NFC] Indentation consistency

test/mtl/metal.jl
Edit: I found the following in the Metal headers:
```objective-c
/*!
@property device
@abstract The device this event can be used with. Will be nil when the event is shared across devices (i.e. MTLSharedEvent).
*/
@property (nullable, readonly) id <MTLDevice> device;
```
Seems to me like `ev.device` is supposed to be `nothing` in this test, and then I don't know why it returns a device under validation or if it that's the actual bug.
I've updated the PR to reflect the new information from the headers.
=> Enabling previously disabled test and mark broken

lib/mps/MPS.jl, lib/mps/command_buf.jl, src/Metal.jl, src/linalg.jl, test/linalg.jl, test/mps/linalg.jl
The high-level wrappers for `LinearAlgebra` don't really belong in `MPS`.
This PR moves the code and tests for those high-level functions.
This is a first step to using MPSGraph where possible for matmul to mitigate #381 where supported by MPSGraph, but this change is an improvement on its own and will reduce noise in the MPSGraph PR.
=> [NFC] Move linear algebra wrappers out of `MPS` lib

src/device/intrinsics/math.jl, test/device/intrinsics/math.jl
Bypasses the conversion to `BigFloat` when converting `pi` and `e` to `Float32` and `Float16` on gpu. Values are taken from the constants in Tables 6.5 and 6.6 of the Metal shading language [specification](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf).
Close #551
=> `Pi` and `e` to `Float32` and `Float16`

lib/mps/random.jl
Optimization mentioned in https://github.com/JuliaGPU/Metal.jl/pull/564#discussion_r1995943912
This won't happen very often as the cpu array has to be page-aligned in memory, and `sizeof` a multiple of a page (16384 bytes), but when it does it cut memory usage in half.
=> Remove copy when possible from cpu rnad using GPU RNG

examples/unified_memory.jl
Split out https://github.com/JuliaGPU/Metal.jl/pull/580/commits/602e4f48b17ed5f0e40b0fdb657365f8440cd1f4 to merge earlier since it was also encountered in another PR: https://buildkite.com/julialang/metal-dot-jl/builds/1881#0196445f-e2c3-4961-9eb1-6819b6b2adab
I don't actually know if this will fix the issue, but this is something that should be fixed regardless
=> Use an appropriate amount of threads in unified memory example

ext/SpecialFunctionsExt.jl, test/device/intrinsics/math.jl, test/mps/ndarray.jl
Tried to turn of KA SpecialFunctions tests without realizing we don't have `gamma` implemented, but that uncovered a bug with our openlibm port of `erf`. 
Best looked at each commit individually. I slightly refactored some tests to make it easier to mark broken, and changed the other tests around for consistency. It now also tests Float16 and Float32 instead of testing Float32 twice.
=> Fix `erf` and a few other improvements

test/device/intrinsics/atomics.jl, test/device/intrinsics/math.jl, test/device/intrinsics/simd.jl, test/device/intrinsics/synchronization.jl, test/mps/linalg.jl, test/mps/ndarray.jl, test/mpsgraphs/core.jl, test/mpsgraphs/linalg.jl, test/mpsgraphs/random.jl, test/mtl/metal.jl, test/mtl/size.jl, test/profiling.jl, test/setup.jl, test/version.jl
Also fixes a bug oversight in the tests for `MPSGraphRandomOpDescriptor`.
I left the specific imports (eg. `using .MPS: something`) in their respective files.
I moved the `BFloat16s` import to setup.jl since it would eventually get moved there with #446 regardless. I left the `SpecialFunctions` in the math intrinsics test file because it's the only set of tests that require it, but I can move it to setup.jl if people think that would be best.
=> Clean up test imports

src/indexing.jl, test/array.jl
Might as well fix it now and the new test will stay relevant.
Close #578
=> Fix findall output type

src/indexing.jl, test/array.jl
Things that should be merged from my struggle with #590.
=> Minor `findall` and `accumulate` tests improvements

Project.toml, README.md, lib/mtl/compile-opts.jl, lib/mtl/libmtl.jl
The errors this fixes only show up when testing with a version of Julia compiled on macOS 26.
I'm thinking of waiting a couple beta versions before adding the rest of the wrappers in case things change.
=> Add bare minimum for macOS 26 Tahoe

src/broadcast.jl, test/array.jl
Fixes a broadcasting issue when the arrays have different dimensions and storage types. 
Previously this MWE would fail:
```julia
x = Metal.zeros(10, 10, storage=Metal.SharedStorage)
y = Metal.zeros(10)
x .+ y # Error: conflicting broadcast rules defined
```
=> Handle broadcasting when storage types are different

src/MetalKernels.jl, src/device/intrinsics/synchronization.jl
KernelAbstractions (influenced by CUDA) states
> After a  statement all read and writes to global and local memory
> from each thread in the workgroup are visible in from all other threads in the
> workgroup.
Fixes https://github.com/JuliaGPU/Metal.jl/issues/608
=> Add `MemoryFlagDevice` to KA.jl's synchronization primitive.

src/mapreduce.jl
Based on https://github.com/JuliaGPU/CUDA.jl/pull/2778
=> Remove the unnecessary reshape during mapreduce

Project.toml, README.md, src/initialization.jl
All tests are passing for current Metal 3 functionality, so we can probably remove this warning for macOS 26. I wouldn't update the README until it's actually released however.
=> Don't warn on macOS 26 and bump version

lib/mtl/events.jl, src/state.jl
Reverts JuliaGPU/Metal.jl#633
The MTLCaptureManager failures seems to be related. Not much info online about how `stopCapture` works but it seems like the capture manager's `isCapturing` property does not change to false until the command buffer status is `MTLCommandBufferStatusCompleted`, which the new synchronization via events method does not wait for.
Will reland after determining how to deal with this for capturing.
=> Revert "Synchronize using `MTLSharedEvent`s"

.buildkite/pipeline.yml, lib/mtl/storage_type.jl, src/array.jl, src/memory.jl, src/pool.jl, test/array.jl
Metal.jl only supports Apple silicon which have unified memory. Managed storage through the MtlArray interface has never been very well supported and it's a pain to maintain whenever it comes up.
The API wrappers are untouched.
If anyone objects, please speak up. I'm curious to hear about why shared storage cannot be used in lieu of managed storage.
Close #642
=> Remove support for `MtlArray`s backed by managed storage.

.github/workflows/Load.yml, test/runtests.jl
Also make architecture detection in the test script a bit more robust.
This was originally to move to buildkite but then github actions `macos-15-intel` runners were [announced](https://github.com/actions/runner-images/issues/13045).
=> Switch to `macos-15-intel` for x64 load tests
